# SPDX-License-Identifier: MIT

noinst_LTLIBRARIES = libcppcommon.la

libcppcommon_la_SOURCES = \
	text-loc.hpp text-loc.cpp \
	text-parse-error.hpp text-parse-error.cpp \
	str-scanner.hpp str-scanner.cpp \
	json-val.hpp json-val.cpp \
	parse-json-as-val.hpp parse-json-as-val.cpp \
	bt2-value-from-json-val.hpp bt2-value-from-json-val.cpp \
	val-req.hpp \
	json-val-req.hpp

EXTRA_DIST = \
	bt2 \
	optional.hpp \
	string_view.hpp \
	uuid-view.hpp \
	nlohmann/json.hpp \
	parse-json.hpp \
	make-unique.hpp \
	safe-ops.hpp \
	data-len.hpp
