# SPDX-License-Identifier: MIT

noinst_LTLIBRARIES = libctf-src-metadata-json.la

libctf_src_metadata_json_la_SOURCES = \
	strings.hpp \
	val-req.cpp val-req.hpp \
	utils.cpp utils.hpp \
	ctf-2-metadata-stream-parser.cpp ctf-2-metadata-stream-parser.hpp \
	scope-fc-from-json-val.cpp scope-fc-from-json-val.hpp \
	json-fcs-with-role.cpp json-fcs-with-role.hpp
